Repository woowa-techcamp-2022/web-moneybook-09, pull requests merged in 2022-07, with the labels that each got.

#4 프로젝트 구조 정하기
  .babelrc
  .eslintrc
  .gitignore
  .prettierrc
  client/index.html
  client/jsconfig.json
  client/src/App.js
  client/src/components/Header/index.js
  client/src/core/Component.js
  client/src/core/CreateDom.js
  client/src/core/Observer.js
  client/src/index.js
  client/src/utils/validation.js
  client/webpack/jsconfigToWebpack.js
  client/webpack/webpack.common.js
  client/webpack/webpack.config.dev.js
  client/webpack/webpack.config.prod.js
  package.json
  server/app.js
  server/bin/www
  server/routes/index.js
Labels: 기능, 프론트엔드, 설정

#7 이슈, PR 템플릿 추가
  .github/ISSUE_TEMPLATE/기본이슈.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .gitmessage
  package.json
Labels: 설정, 문서

#9 pr,issue 템플릿 develop 브랜치에도 적용
  .github/ISSUE_TEMPLATE/기본이슈.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서

#8 프론트 구조 잡는 부분 Release
  .babelrc
  .eslintrc
  .gitignore
  .prettierrc
  client/index.html
  client/jsconfig.json
  client/src/App.js
  client/src/components/Header/index.js
  client/src/core/Component.js
  client/src/core/CreateDom.js
  client/src/core/Observer.js
  client/src/index.js
  client/src/utils/validation.js
  client/webpack/jsconfigToWebpack.js
  client/webpack/webpack.common.js
  client/webpack/webpack.config.dev.js
  client/webpack/webpack.config.prod.js
  package.json
  server/app.js
  server/bin/www
  server/routes/index.js
Labels: 기능, 프론트엔드, 문서

#11 SPA Router 작성 완료
  client/src/App.js
  client/src/core/Component.js
  client/src/core/Observer.js
  client/src/core/Route.js
  client/src/pages/Account.js
  client/src/pages/Calendar.js
  client/src/pages/Statistic.js
  client/src/utils/stringUtils.js
  client/webpack/webpack.config.dev.js
  server/app.js
  server/routes/index.js
Labels: 백엔드, 기능, 프론트엔드

#14 인스턴스 설정 및 서버 개발환경 구축
  package.json
  server/app.js
  server/db/checkTable/category.js
  server/db/checkTable/history.js
  server/db/checkTable/paymentMethod.js
  server/db/loader.js
Labels: 백엔드, 설정, 페어

#15 history API 중 Model과 Service 로직
  server/models/history.js
  server/services/history.js
  server/utils/format.js
  server/utils/query.js
  server/utils/time.js
Labels: 백엔드, 기능, 페어

#18 프론트엔드 전역 상태 및 전역 스타일링 결정
  .eslintrc
  .prettierrc
  client/src/GlobalStyle.css
  client/src/core/CreateDom.js
  client/src/core/Observer.js
  client/src/core/Route.js
  client/src/icons/calendar.js
  client/src/icons/chart.js
  client/src/icons/check.js
  client/src/icons/fileText.js
  client/src/utils/validation.js
  package.json
  server/app.js
  server/models/history.js
  server/utils/format.js
  server/utils/query.js
  server/utils/time.js
Labels: 리팩토링, 기능, 프론트엔드, 페어

#22 Icon을 CreateDom 함수로 생성할 때 오류 해결
  client/jsconfig.json
  client/src/GlobalStyle.css
  client/src/icons/calendar.js
  client/src/icons/chart.js
  client/src/icons/check.js
  client/src/icons/downArrow.js
  client/src/icons/fileText.js
  client/src/icons/index.js
  client/src/index.js
  client/src/utils/svgDomCreator.js
Labels: 기능, 프론트엔드, 오류

#23 Header 컴포넌트 작성 및 월 이동
  client/src/App.js
  client/src/GlobalStyle.css
  client/src/components/Header/index.css
  client/src/components/Header/index.js
  client/src/core/CreateDom.js
  client/src/core/Route.js
  client/src/store/controlDate.js
  client/src/utils/date.js
Labels: 기능, 프론트엔드

#26 Category API 기능 개발
  server/app.js
  server/models/category.js
  server/routes/category.js
  server/routes/index.js
  server/services/category.js
  server/utils/format.js
  server/utils/query.js
Labels: 리팩토링, 백엔드, 기능, 오류

#28 Payment Method API 기능 개발
  server/models/paymentMethod.js
  server/routes/index.js
  server/routes/paymentMethod.js
  server/services/category.js
  server/services/paymentMethod.js
  server/utils/format.js
Labels: 백엔드, 기능

#29 History API 기능 CRUD & 최근 6개월 합
  server/models/history.js
  server/routes/history.js
  server/routes/index.js
  server/services/history.js
  server/utils/format.js
Labels: 백엔드, 기능

#31 History API 모든 기능 구동 완료 v1
  server/models/category.js
  server/models/history.js
  server/models/paymentMethod.js
  server/routes/category.js
  server/routes/history.js
  server/routes/paymentMethod.js
  server/services/category.js
  server/services/history.js
  server/services/paymentMethod.js
  server/utils/errorMessages.js
  server/utils/query.js
  server/utils/time.js
Labels: 리팩토링, 백엔드, 기능

#32 프론트에서 Fetch 사용하는 방식 통일 및 서버 Cors 설정
  client/src/App.css
  client/src/App.js
  client/src/apis/index.js
  client/src/components/AccountForm/accountForm.css
  client/src/utils/request.js
  package.json
  server/app.js
Labels: 백엔드, 기능, 프론트엔드, 설정

#36 history input기능 완성
  client/src/apis/categoryApi.js
  client/src/apis/index.js
  client/src/apis/paymentMethodApi.js
  client/src/components/AccountForm/AmountInput.js
  client/src/components/AccountForm/CategoryDropdown.js
  client/src/components/AccountForm/FormInput.js
  client/src/components/AccountForm/customEvent.js
  client/src/components/AccountForm/format.js
  client/src/components/AccountForm/index.js
  client/src/components/AccountForm/paymentDropdown.js
  client/src/components/AccountForm/validation.js
  client/src/components/Modal/CategoryAddForm.js
  client/src/components/Modal/CategoryDeleteForm.js
  client/src/components/Modal/PaymentMethodAddForm.js
  client/src/components/Modal/PaymentMethodDeleteForm.js
  client/src/components/Modal/index.js
  client/src/pages/Account.js
  client/src/store/categories.js
  client/src/store/controlDate.js
  client/src/store/historyState.js
  client/src/store/modal.js
  client/src/store/modalState.js
  client/src/store/paymentMethods.js
  client/src/store/selectedHistory.js
  client/src/utils/compareObject.js
  client/webpack/jsconfigToWebpack.js
  server/models/history.js
Labels: 기능, 프론트엔드

#35 Account History 컴포넌트 개발
  client/src/App.css
  client/src/App.js
  client/src/GlobalStyle.css
  client/src/apis/history.js
  client/src/components/AccountForm/accountForm.css
  client/src/components/Header/index.css
  client/src/components/Header/index.js
  client/src/components/History/Details.css
  client/src/components/History/Details.js
  client/src/components/History/Summary.css
  client/src/components/History/Summary.js
  client/src/components/History/index.css
  client/src/components/History/index.js
  client/src/core/CreateDom.js
  client/src/pages/Account.css
  client/src/pages/Account.js
  client/src/store/histories.js
  client/src/utils/date.js
  server/models/history.js
  server/services/history.js
  server/utils/format.js
Labels: 기능, 프론트엔드

#39 메인 화면 - 데이터 연결 작업 & 일부 UX 개선
  client/src/App.css
  client/src/App.js
  client/src/components/AccountForm/AmountInput.js
  client/src/components/AccountForm/FormInput.js
  client/src/components/AccountForm/index.css
  client/src/components/AccountForm/index.js
  client/src/components/AccountForm/paymentDropdown.js
  client/src/components/AccountForm/validation.js
  client/src/components/History/Details.css
  client/src/components/History/Details.js
  client/src/components/History/Summary.js
  client/src/components/History/index.js
  client/src/components/Modal/PaymentMethodAddForm.js
  client/src/components/Modal/PaymentMethodDeleteForm.js
  client/src/core/Observer.js
  client/src/store/categories.js
  client/src/store/controlDate.js
  client/src/store/histories.js
  client/src/store/loader.js
  client/src/store/paymentMethods.js
  client/src/store/selectedHistory.js
  client/src/utils/compareObject.js
  client/src/utils/format.js
  server/db/checkTable/category.js
  server/db/checkTable/history.js
Labels: 리팩토링, 기능, 프론트엔드, 오류

#41 Calendar 컴포넌트 개발 및 스타일링
  client/src/App.css
  client/src/GlobalStyle.css
  client/src/pages/Calendar.css
  client/src/pages/Calendar.js
  client/src/utils/date.js
  client/src/utils/format.js
Labels: 기능, 프론트엔드

#46 꺾은 선 그래프 작성하기
  client/src/apis/history.js
  client/src/components/History/Details.css
  client/src/components/History/Details.js
  client/src/components/Statistic/DoughnutChart/index.js
  client/src/components/Statistic/Expenditures/index.css
  client/src/components/Statistic/Expenditures/index.js
  client/src/components/Statistic/LineChart/index.js
  client/src/components/Statistic/PaymentReport/StatisticTable.js
  client/src/components/Statistic/PaymentReport/index.css
  client/src/components/Statistic/PaymentReport/index.js
  client/src/pages/Statistic.css
  client/src/pages/Statistic.js
  client/src/store/expenditures.js
  client/src/store/recentSum.js
  client/src/utils/easing.js
Labels: 기능, 프론트엔드, 오류, 페어

#52 배포 시 긴급 오류들 해결
  client/favicon.ico
  client/src/components/Statistic/PaymentReport/index.js
  client/src/store/histories.js
  client/webpack/webpack.common.js
  package.json
Labels: 기능, 프론트엔드
